name: ESLint
description: "Lint source"
author: "shopware AG"
branding:
  color: "blue"
  icon: "download"

inputs:
  extensionName:
    description: "Your extension name"
    required: true
  projectPath:
    description: "Path to the js project to be linted. Checks the administartion app by default"
    default: src/Resources/app/administration
  npmLintCmd:
    description: "The npm command to run"
    default: lint
  shopwareVersion:
    description: |
      With the default `.auto`, the workflow tries to find a shopware version using the shopware-version action.

      For example, if the current ref is next-1234, it will try to find the ref next-1234 in shopware/shopware. If there's no matching ref, it will use shopwareVersionFallback
    required: false
    default: ".auto"
  shopwareVersionFallback:
    description: Fallback version in case there's no matching branch
    required: false
    default: trunk
  shopware-repository:
    description: The shopware repository to checkout
    required: true
    default: shopware/shopware
  shopware-github-token:
    description: Token used for checking out the shopware repository
    required: true
    default: ${{ github.token }}
  forceInstallAdminDeps:
    description: Install platform admin deps
    default: ""
    required: false
  forceInstallStorefrontDeps:
    description: Install platform storefront deps
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - uses: shopware/github-actions/shopware-version@main
      with:
        fallback: ${{ inputs.shopwareVersionFallback }}
        repo: ${{ inputs.shopware-repository }}
        shopware-github-token: ${{ inputs.shopware-github-token }}
      id: version
      if: ${{ inputs.shopwareVersion == '.auto' }}
    - name: Clone Shopware
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.shopware-repository }}
        ref: ${{ steps.version.outputs.shopware-version || inputs.shopwareVersion }}
        token: ${{ inputs.shopware-github-token }}

    - name: Clone Extension
      uses: actions/checkout@v4
      with:
        path: custom/plugins/${{ inputs.extensionName }}

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"

    - name: Install admin deps
      shell: bash
      if: ${{ inputs.forceInstallAdminDeps || contains(inputs.projectPath, 'administration') }}
      working-directory: src/Administration/Resources/app/administration
      run: npm ci --no-audit --no-fund --prefer-offline

    - name: Install storefront deps
      shell: bash
      if: ${{ inputs.forceInstallStorefrontDeps || contains(inputs.projectPath, 'storefront') }}
      working-directory: src/Storefront/Resources/app/storefront
      run: npm ci --no-audit --no-fund --prefer-offline

    - name: Install Plugin Dependencies
      shell: bash
      working-directory: custom/plugins/${{ inputs.extensionName }}/${{ inputs.projectPath }}
      run: npm install --no-audit --no-fund --prefer-offline

    - name: Run Lint command
      shell: bash
      working-directory: custom/plugins/${{ inputs.extensionName }}/${{ inputs.projectPath }}
      run: npm run ${{ inputs.npmLintCmd }}
