name: "Extension Verifier"
description: "Extension Verifier"
author: "shopware AG"
branding:
  color: "blue"
  icon: "download"
inputs:
  version:
    description: "The of extension verifier to use"
    required: false
    default: "latest"
  action:
    description: "The action to run (check, format)"
    required: true
    default: "check"
  check-against:
    description: "The version to check against"
    required: false
    default: "highest"

runs:
  using: "composite"
  steps:
    - name: Install Shopware-CLI
      uses: shopware/shopware-cli-action@v1
    - name: Run verifier
      if: inputs.action == 'check'
      shell: bash
      run: shopware-cli extension validate --full --check-against ${{ inputs.check-against }} .
    - name: Run formatter
      if: inputs.action == 'format'
      shell: bash
      run: shopware-cli extension format . --dry-run
