name: "Extension Verifier"
description: "Extension Verifier"
author: "shopware AG"
branding:
  color: "blue"
  icon: "download"
inputs:
  version:
    description: "The extension verifier to use"
    required: false
    default: "latest"
  action:
    description: "The action to run (check, format)"
    required: true
    default: "check"
  check-against:
    description: "The version to check against"
    required: false
    default: "highest"

runs:
  using: "composite"
  steps:
    - name: Pull verifier
      run: docker pull ghcr.io/shopwarelabs/extension-verifier:${{ inputs.version }}
      shell: bash
    - name: Run verifier
      if: inputs.action == 'check'
      shell: bash
      run: docker run --rm -e GITHUB_STEP_SUMMARY -e GITHUB_ACTIONS -v $GITHUB_STEP_SUMMARY:$GITHUB_STEP_SUMMARY -v $(pwd):/ext ghcr.io/shopwarelabs/extension-verifier:${{ inputs.version }} check /ext --check-against ${{ inputs.check-against }}
    - name: Run formatter
      if: inputs.action == 'format'
      shell: bash
      run: docker run --rm -e GITHUB_STEP_SUMMARY -e GITHUB_ACTIONS -v $GITHUB_STEP_SUMMARY:$GITHUB_STEP_SUMMARY -v $(pwd):/ext ghcr.io/shopwarelabs/extension-verifier:${{ inputs.version }} format /ext --dry-run
