name: cs-fixer
description: "PHP-CS-Fixer action"
author: "shopware AG"
branding:
  color: "blue"
  icon: "download"

inputs:
  rules:
    required: false
    default: "@PER-CS2.0,no_unused_imports"
    description: Default rules to check with php-cs-fixer

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Setup PHP
      uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
      with:
        php-version: 8.2
        tools: php-cs-fixer:3.63.2, cs2pr

    - name: Run PHP CS Fixer
      shell: bash
      run: |
        if [[ -n "${{ inputs.rules }}" ]]; then
          export RULES="--rules=${{ inputs.rules }}"
        fi
        php-cs-fixer fix . --dry-run ${RULES} --format=checkstyle | cs2pr
