name: cs-fixer
description: "PHP-CS-Fixer action"
author: "shopware AG"
branding:
  color: "blue"
  icon: "download"

inputs:
  rules:
    required: false
    default: "@PER-CS2.0,no_unused_imports"
    description: Default rules to check with php-cs-fixer

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        tools: php-cs-fixer, cs2pr

    - name: Run PHP CS Fixer
      shell: bash
      run: |
        if [[ -n "${{ inputs.rules }}" ]]; then
          export RULES="--rules=${{ inputs.rules }}"
        fi
        php-cs-fixer fix . --dry-run ${RULES} --format=checkstyle | cs2pr
