name: shopware-version
description: "Action to get the shopware version that is matching the current branch. Returns a fallback if no matching branch is found."
author: "shopware AG"
branding:
  color: "blue"
  icon: "download"

inputs:
  fallback:
    description: The fallback that is returned if there's no matching branch
    default: trunk
    required: false
  repo:
    description: The repo where to look for matching refs
    default: shopware/shopware
    required: false
  shopware-github-token:
    description: Token used for checking out the shopware repository
    required: true
    default: ${{ github.token }}

outputs:
  shopware-version:
    description: The matching shopware version or fallback
    value: ${{ steps.get-version.outputs.shopware-version }}

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        git config --global "http.https://github.com/${{ inputs.repo }}".extraheader "AUTHORIZATION: basic $(echo -n "x-access-token:${{ inputs.shopware-github-token }}" | base64 -w0)"

    - name: Get shopware version
      id: get-version
      shell: bash
      env:
        REF: "${{ github.ref }}"
        BASE_REF: "${{ github.base_ref }}"
        HEAD_REF: "${{ github.head_ref }}"
        REPO: "${{ inputs.repo }}"
        CURRENT_REPO: "${{ github.repository }}"
        FALLBACK: "${{ inputs.fallback || 'trunk' }}"
      run: ${GITHUB_ACTION_PATH}/shopware-version.bash

    - shell: bash
      run: |
        git config --global --unset "http.https://github.com/${{ inputs.repo }}".extraheader
