name: shopware-version
description: "Action to get the shopware version that is matching the current branch. Returns a fallback if no matching branch is found."
author: "shopware AG"
branding:
  color: "blue"
  icon: "download"

inputs:
  fallback:
    description: The fallback that is returned if there's no matching branch
    default: trunk
    required: false
  repo:
    description: The repo where to look for matching refs
    default: shopware/shopware
    required: false

outputs:
  shopware-version:
    description: The matching shopware version or fallback
    value: ${{ steps.get-version.outputs.shopware-version }}

runs:
  using: "composite"
  steps:
    - name: Get shopware version
      id: get-version
      shell: bash
      env:
        REF: "${{ github.ref }}"
        BASE_REF: "${{ github.base_ref }}"
        HEAD_REF: "${{ github.head_ref }}"
        REPO: "${{ inputs.repo }}"
        CURRENT_REPO: "${{ github.repository }}"
        FALLBACK: "${{ inputs.fallback || 'trunk' }}"
      run: ${GITHUB_ACTION_PATH}/shopware-version.bash
