name: Build Extension Zip
on:
  workflow_call:
    inputs:
      extensionName:
        description: "Your extension name"
        required: true
        type: string
      path:
        description: "Path to your bundle"
        required: false
        type: string
        default: "."
jobs:
  run:
    name: Build and Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install shopware-cli
        uses: shopware/shopware-cli-action@v3
      - name: Build
        run: shopware-cli extension zip "${{ inputs.path }}" --git-commit "${{ github.sha }}" --release
      - name: Rename
        run: mv ${{ inputs.extensionName }}-${{ github.sha }}.zip ${{ inputs.extensionName }}.zip
      - name: Validate
        run: shopware-cli extension validate ${{ inputs.extensionName }}.zip
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ inputs.extensionName }}
          path: ${{ inputs.extensionName }}.zip
