name: Check pinned GitHub Action versions

on:
  pull_request:
    paths:
      - '**/*.yml'
      - '**/*.yaml'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: shopware/github-actions/check-pinned-actions@main
